### **Username**: suneelraju160
**Name**: Kucharlapati Venkata Suneel Raju

Data Science latest assignments - 16 Aug 2025

**Assignment 2: Data Structures, Functions, Numpy and Pandas**

**Date**: 28 Nov 2025

# PYTHON ASSIGNMENT
## Data Structures, Functions, Numpy and Pandas

### Section A: Data Struture and Control Structures

**Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.**

In [1]:
a = [10,20,30,40,50]
print("The list is:", a)
a.append(60)
print("After append:", a)
a.extend([70,80])
print("After extend:", a)
a.insert(0,5)
print("After insert:", a)
a.remove(30)
print("After remove:", a)
a.pop(2)
print("After pop:", a)
a.index(40)
print("The index of 40 is:", a)
a.count(50)
print("Count:", a)
a.sort()
print("After sort:", a)
a.reverse()
print("Reverse of a is", a)
a.clear()
print("Clear:", a)

The list is: [10, 20, 30, 40, 50]
After append: [10, 20, 30, 40, 50, 60]
After extend: [10, 20, 30, 40, 50, 60, 70, 80]
After insert: [5, 10, 20, 30, 40, 50, 60, 70, 80]
After remove: [5, 10, 20, 40, 50, 60, 70, 80]
After pop: [5, 10, 40, 50, 60, 70, 80]
The index of 40 is: [5, 10, 40, 50, 60, 70, 80]
Count: [5, 10, 40, 50, 60, 70, 80]
After sort: [5, 10, 40, 50, 60, 70, 80]
Reverse of a is [80, 70, 60, 50, 40, 10, 5]
Clear: []


**Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.**

In [2]:
students = ('Ram', 'Sita', 'Laxman')
students[1] = 'Hanuman'

TypeError: 'tuple' object does not support item assignment

Explanation: Tuples are immutable. Once the value is assigned, it cannot be changed.

**Create a set of integers with some duplicate values. Print the set and explain the output.**

In [3]:
a={10, 20,30,40, 40, 20, 50, 10}
print(a)

{50, 20, 40, 10, 30}


Explanation: A set stores unique values and do not keep duplicate values.

**Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.**

In [4]:
details = {'name':"Suneel", 'age':21, 'city':"Vizag"}
details['age'] = 22
details['email'] = "abc1@gmail.com"
print(details)

{'name': 'Suneel', 'age': 22, 'city': 'Vizag', 'email': 'abc1@gmail.com'}


**Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.**

In [5]:
age = int(input("Enter the age: "))
if age > 18:
  print("Eligible to vote")
else:
  print("Not eligible to vote")

Enter the age: 27
Eligible to vote


**Given a 'marks' variable, print the grade:**
**- 90 and above: 'A'**
**- 75–89: 'B'**
**- 50–74: 'C'**
**- Below 50: 'Fail'**


In [6]:
marks = int(input("Enter the marks: "))
if marks >= 90:
  print("Grade: A")
elif marks >= 75 and marks <= 89:
  print("Grade: B")
elif marks >= 50 and marks <= 74:
  print("Grade: C")
else:
  print("Grade: Fail")

Enter the marks: 92
Grade: A


**Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.**

In [7]:
num = int(input("Enter the number: "))
if num > 0:
  if num % 2 == 0:
    print("Positive and even")
  else:
    print("Positive and odd")
if num == 0:
  print("Zero")
if num < 0:
  print("Negative")

Enter the number: 0
Zero


## NUMPY

**8.	Create:**

**- A scalar using np.array(5)**

**- A 1D array with values 1 to 5**

**- A 2D array (2x3) with values from 10 to 60 in steps of 10**


In [8]:
import numpy as np

# Scalar
scalar = np.array(5)
print("Scalar:\n", scalar)

# 1D array with values 1 to 5
arr_1d = np.array([1, 2, 3, 4, 5])
print("\n1D Array:\n", arr_1d)

# 2D array (2x3) with values 10 to 60 in steps of 10
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60]])
print("\n2D Array:\n", arr_2d)


Scalar:
 5

1D Array:
 [1 2 3 4 5]

2D Array:
 [[10 20 30]
 [40 50 60]]


**9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().**

In [9]:
import numpy as np

random_arr = np.random.randint(0, 101, size=(4,4))
print("4x4 Random Integer Array:\n", random_arr)


4x4 Random Integer Array:
 [[ 34  60  75 100]
 [ 59  94  99  29]
 [ 60  86  16  62]
 [ 89  95  97  90]]


**10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.**

In [10]:
import numpy as np
import pandas as pd

# Creating a 3x3 array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Converting to DataFrame with column names
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])

print("DataFrame:\n", df)


DataFrame:
    A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


**11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:**

**- Use .info(), .describe()**

**- Select 'Name' and 'City' columns**

**- Drop 'City' column**

**- Fill any missing values in 'Salary' column with the mean**

**- Remove any duplicate rows**

In [1]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Ravi", "Sita", "Aman", "John", "Rani",
             "Meera", "Asha", "Sara", "Kiran", "Rani"],
    "Age": [25, 30, 22, 28, 25, 27, 24, 30, 29, 25],
    "City": ["Delhi", "Mumbai", "Chennai", "Delhi", "Delhi",
             "Hyderabad", "Pune", "Mumbai", "Chennai", "Delhi"],
    "Salary": [50000, 60000, np.nan, 55000, 50000,
               58000, 52000, np.nan, 61000, 50000]
}

df = pd.DataFrame(data)


print("DataFrame Info:")
print(df.info())


print("\nStatistics:")
print(df.describe())


print("\nSelected Columns (Name, City):")
print(df[['Name', 'City']])


df_dropped = df.drop('City', axis=1)
print("\nDataFrame after dropping 'City':")
print(df_dropped)


mean_salary = df['Salary'].mean()
df['Salary'] = df['Salary'].fillna(mean_salary)

print("\nDataFrame after filling missing Salary values:")
print(df)


df_no_duplicates = df.drop_duplicates()
print("\nDataFrame after removing duplicates:")
print(df_no_duplicates)


DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

Statistics:
             Age       Salary
count  10.000000      8.00000
mean   26.500000  54500.00000
std     2.718251   4659.85898
min    22.000000  50000.00000
25%    25.000000  50000.00000
50%    26.000000  53500.00000
75%    28.750000  58500.00000
max    30.000000  61000.00000

Selected Columns (Name, City):
    Name       City
0   Ravi      Delhi
1   Sita     Mumbai
2   Aman    Chennai
3   John      Delhi
4   Rani      Delhi
5  Meera  Hyderabad
6   Asha       Pune
7   Sara     Mumbai
8  Kiran    Chennai
9   Rani      Delhi

DataFrame after dropping 'City':
    Name  Age   Sala